name: dockercicd

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Envfile
        uses: SpicyPizza/create-env@v1.3
        with:
          envkey_ERISKEY: ${{ secrets.ERISKEY }}
          envkey_AZUREPAT: ${{ secrets.AZUREPAT }}
          envkey_ORGNAME: "lukesdata"
          envkey_PROJECTNAME: "lukegates"
      - name: Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to repo
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: luke:chatbot:latest